version: "3.8"
services:
  api:
    build: .
    container_name: c_api
    ports:
      - "10000:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: c_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
